// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsqfsevgboqyslvigpon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzcWZzZXZnYm9xeXNsdmlncG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzAyMDEsImV4cCI6MjA3MDk0NjIwMX0.meuuDqA02H3UTeSq5Y7LQNrOuujT13JC6EXLelTRK-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});